apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cc-tomcat-hpa
  namespace: cc-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cc-tomcat-deploy
  minReplicas: 3           # 기본 3개
  maxReplicas: 10          # 최대 10개까지
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 35   # 파드 평균 CPU 60% 넘으면 증설
